### ISSUE TITLE
Andrhei Henrique | Definição de Produto

### ISSUE THREAD

**Issue by Wagner-Oliveira** [FusionAppsStartup/FusionFood#5]
Data de Inicio: 09/01/2018
Data Final: 18/01/2018
Assunto:
Preparar uma apresentação de Produtos e/ou Serviços do seu departamento com os seguintes requisitos:
(Simulação de Venda a um cliente)
- O que faz?
- Como Funciona?
- Para quê alguém compraria?
- Definir Custo com base em pesquisas de mercado
- Prazo de Entrega ao Cliente
- Por que ele merece estar nas propostas da FusionApps?

**Comment by Andrhei** [comment]
PRODUTO: FusionFood.

O que faz?
     *Sistema PDV e ERP;

Como Funciona?
       *Possui quatro perfis: Garçom, Cozinha, Caixa E Administrador;
        	-Administrador: Faz toda a parte de cadastros e tem acesso ao ERP;
	        -Garçom: Faz pedidos que são automaticamente encaminhados para a cozinha;
	        -Cozinha: Tem uma lista com os pedidos que foram feitos e quando concluídos são 		  
                                encaminhados para o Caixa;
	        -Caixa: Fechamento de pedidos e de caixa diário;

Para quê alguém compraria?
       *Para facilitar a comunicação em um restaurante e diminuir erros humanos.

Definir Custo com base em pesquisas de mercado:
        *A partir de R$50,00/mês à R$200,00/mês;
	*Impressoras, Bobinas e Tintas;
	*Balanças;
	*Leitores de Códigos;
	*Instalação.

Prazo de Entrega ao Cliente:
        *A partir do momento de fechamento de contrato três dias no máximo.

Por que ele merece estar nas propostas da FusionApps?
         *Além de ser um sistema que precisa somente de alguns ajustes, tem muito potencial pelo 
          crescimento da automatização dos restaurantes;
