### ISSUE TITLE
Wagner E/OU Mateus | Pesquisa de Atividades da Concorrência

### ISSUE THREAD

**Issue by Wagner-Oliveira** [FusionAppsStartup/FusionFood#9]
Data de Inicio: 09/01/2018
Data Final: 25/01/2018
Assunto:
Fazer uma pesquisa com informações das principais concorrentes de nossa empresa, buscando informações tais como: o que ela faz, quanto custa, em quais regiões elas atuam e elaborar um resumo dos resultados obtidos

**Comment by MateusJFabricio** [comment]
Este issue esta repetido.
